all:
	TCPServer  TCPClient

TCPServer : solution_9_TCPServer.c FileOperation.h
	gcc -o solution_9_TCPServer.c FileOpearation.h

TCPClient : solution_9_TCPClient.c FileOperation.h
	gcc -o solution_9_TCPClient.c FileOpration.h

